import { jsPDF } from "jspdf";
import fs from "fs";

const content = [
"# Complete Production-Ready Full-Stack Application Documentation",
"Product Name: TaskFlow Pro",
"Stack: Next.js (TypeScript) + Express (TypeScript) + Prisma + PostgreSQL",
"",
"## 1) PROJECT STRUCTURE",
"",
"```txt",
"taskflow-pro/",
"  apps/",
"    web/",
"      app/",
"        (marketing)/page.tsx",
"        (auth)/login/page.tsx",
"        (auth)/register/page.tsx",
"        (auth)/forgot-password/page.tsx",
"        (dashboard)/layout.tsx",
"        (dashboard)/dashboard/page.tsx",
"        (dashboard)/projects/page.tsx",
"        (dashboard)/projects/[projectId]/page.tsx",
"        (dashboard)/tasks/[taskId]/page.tsx",
"      components/",
"        ui/",
"        layout/",
"        auth/",
"        projects/",
"        tasks/",
"      features/",
"        auth/",
"        projects/",
"        tasks/",
"      stores/",
"        auth.store.ts",
"        project.store.ts",
"        task.store.ts",
"      lib/",
"        api-client.ts",
"        env.ts",
"        utils.ts",
"      types/",
"      middleware.ts",
"      tailwind.config.ts",
"      postcss.config.js",
"      package.json",
"",
"    api/",
"      src/",
"        app.ts",
"        server.ts",
"        config/",
"          env.ts",
"          logger.ts",
"        routes/",
"          index.ts",
"          auth.routes.ts",
"          users.routes.ts",
"          organizations.routes.ts",
"          projects.routes.ts",
"          tasks.routes.ts",
"          comments.routes.ts",
"        controllers/",
"          auth.controller.ts",
"          users.controller.ts",
"          projects.controller.ts",
"          tasks.controller.ts",
"          comments.controller.ts",
"        services/",
"          auth.service.ts",
"          users.service.ts",
"          projects.service.ts",
"          tasks.service.ts",
"          comments.service.ts",
"        repositories/",
"          user.repository.ts",
"          organization.repository.ts",
"          membership.repository.ts",
"          project.repository.ts",
"          task.repository.ts",
"          comment.repository.ts",
"          refresh-token.repository.ts",
"        middlewares/",
"          auth.middleware.ts",
"          rbac.middleware.ts",
"          validate.middleware.ts",
"          error.middleware.ts",
"          rate-limit.middleware.ts",
"        validators/",
"          auth.schemas.ts",
"          project.schemas.ts",
"          task.schemas.ts",
"          comment.schemas.ts",
"        utils/",
"          jwt.ts",
"          password.ts",
"          response.ts",
"          http-error.ts",
"        prisma/",
"          schema.prisma",
"          migrations/",
"          seed.ts",
"      package.json",
"",
"  packages/",
"    shared/",
"      src/",
"        dto/",
"        enums/",
"        zod/",
"      package.json",
"",
"  infra/",
"    docker/",
"      api.Dockerfile",
"      web.Dockerfile",
"    docker-compose.yml",
"    nginx.conf",
"",
"  .github/workflows/ci.yml",
"  pnpm-workspace.yaml",
"  README.md",
"```",
"",
"Folder explanation:",
"- apps/web: complete frontend UI layer, route groups, components, stores, client API integration.",
"- apps/api: API layer + controller/service/repository clean architecture.",
"- packages/shared: shared DTOs, enums, validation contracts to avoid frontend/backend drift.",
"- infra: containerization and reverse proxy config for production deployment.",
"",
"## 2) DATABASE SCHEMA (PRISMA + POSTGRESQL)",
"",
"```prisma",
"generator client {",
"  provider = \"prisma-client-js\"",
"}",
"",
"datasource db {",
"  provider = \"postgresql\"",
"  url      = env(\"DATABASE_URL\")",
"}",
"",
"enum Role { OWNER ADMIN MANAGER MEMBER VIEWER }",
"enum TaskStatus { BACKLOG TODO IN_PROGRESS IN_REVIEW DONE CANCELED }",
"enum TaskPriority { LOW MEDIUM HIGH CRITICAL }",
"",
"model User {",
"  id               String   @id @default(cuid())",
"  email            String   @unique @db.VarChar(320)",
"  passwordHash     String   @db.VarChar(255)",
"  fullName         String   @db.VarChar(120)",
"  avatarUrl        String?  @db.VarChar(2048)",
"  isActive         Boolean  @default(true)",
"  emailVerifiedAt  DateTime?",
"  lastLoginAt      DateTime?",
"  createdAt        DateTime @default(now())",
"  updatedAt        DateTime @updatedAt",
"",
"  memberships      Membership[]",
"  createdProjects  Project[] @relation(\"ProjectCreator\")",
"  reportedTasks    Task[]    @relation(\"TaskReporter\")",
"  comments         Comment[]",
"  refreshTokens    RefreshToken[]",
"  resetTokens      PasswordResetToken[]",
"  assignedTasks    TaskAssignee[]",
"}",
"",
"model Organization {",
"  id          String   @id @default(cuid())",
"  name        String   @db.VarChar(120)",
"  slug        String   @unique @db.VarChar(120)",
"  createdAt   DateTime @default(now())",
"  updatedAt   DateTime @updatedAt",
"",
"  memberships Membership[]",
"  projects    Project[]",
"",
"  @@index([slug])",
"}",
"",
"model Membership {",
"  id             String       @id @default(cuid())",
"  organizationId String",
"  userId         String",
"  role           Role         @default(MEMBER)",
"  joinedAt       DateTime     @default(now())",
"",
"  organization   Organization @relation(fields: [organizationId], references: [id], onDelete: Cascade)",
"  user           User         @relation(fields: [userId], references: [id], onDelete: Cascade)",
"",
"  @@unique([organizationId, userId])",
"  @@index([userId])",
"  @@index([organizationId, role])",
"}",
"",
"model Project {",
"  id             String   @id @default(cuid())",
"  organizationId String",
"  name           String   @db.VarChar(120)",
"  slug           String   @db.VarChar(120)",
"  description    String?  @db.Text",
"  createdById    String",
"  archivedAt     DateTime?",
"  createdAt      DateTime @default(now())",
"  updatedAt      DateTime @updatedAt",
"",
"  organization   Organization @relation(fields: [organizationId], references: [id], onDelete: Cascade)",
"  createdBy      User         @relation(\"ProjectCreator\", fields: [createdById], references: [id], onDelete: Restrict)",
"  members        ProjectMember[]",
"  tasks          Task[]",
"",
"  @@unique([organizationId, slug])",
"  @@index([organizationId])",
"}",
"",
"model ProjectMember {",
"  id         String   @id @default(cuid())",
"  projectId  String",
"  userId     String",
"  role       Role     @default(MEMBER)",
"  addedAt    DateTime @default(now())",
"",
"  project    Project  @relation(fields: [projectId], references: [id], onDelete: Cascade)",
"  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade)",
"",
"  @@unique([projectId, userId])",
"  @@index([userId])",
"}",
"",
"model Task {",
"  id          String       @id @default(cuid())",
"  projectId   String",
"  taskNumber  Int",
"  title       String       @db.VarChar(180)",
"  description String?      @db.Text",
"  status      TaskStatus   @default(TODO)",
"  priority    TaskPriority @default(MEDIUM)",
"  dueDate     DateTime?",
"  reporterId  String",
"  createdAt   DateTime     @default(now())",
"  updatedAt   DateTime     @updatedAt",
"",
"  project     Project      @relation(fields: [projectId], references: [id], onDelete: Cascade)",
"  reporter    User         @relation(\"TaskReporter\", fields: [reporterId], references: [id], onDelete: Restrict)",
"  assignees   TaskAssignee[]",
"  comments    Comment[]",
"",
"  @@unique([projectId, taskNumber])",
"  @@index([projectId, status])",
"  @@index([projectId, priority])",
"  @@index([dueDate])",
"}",
"",
"model TaskAssignee {",
"  id         String   @id @default(cuid())",
"  taskId     String",
"  userId     String",
"  assignedAt DateTime @default(now())",
"",
"  task       Task     @relation(fields: [taskId], references: [id], onDelete: Cascade)",
"  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade)",
"",
"  @@unique([taskId, userId])",
"  @@index([userId])",
"}",
"",
"model Comment {",
"  id        String   @id @default(cuid())",
"  taskId    String",
"  authorId  String",
"  body      String   @db.Text",
"  createdAt DateTime @default(now())",
"  updatedAt DateTime @updatedAt",
"",
"  task      Task     @relation(fields: [taskId], references: [id], onDelete: Cascade)",
"  author    User     @relation(fields: [authorId], references: [id], onDelete: Restrict)",
"",
"  @@index([taskId, createdAt])",
"}",
"",
"model RefreshToken {",
"  id         String   @id @default(cuid())",
"  userId     String",
"  tokenHash  String   @unique @db.VarChar(255)",
"  expiresAt  DateTime",
"  revokedAt  DateTime?",
"  createdAt  DateTime @default(now())",
"",
"  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade)",
"",
"  @@index([userId, expiresAt])",
"}",
"",
"model PasswordResetToken {",
"  id         String   @id @default(cuid())",
"  userId     String",
"  tokenHash  String   @unique @db.VarChar(255)",
"  expiresAt  DateTime",
"  usedAt     DateTime?",
"  createdAt  DateTime @default(now())",
"",
"  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade)",
"",
"  @@index([userId, expiresAt])",
"}",
"```",
"",
"Schema best practices applied:",
"- fully normalized many-to-many via junction tables.",
"- unique and composite constraints for business integrity.",
"- targeted indexes for performance-critical filters.",
"- enum constraints for role and state correctness.",
"",
"## 3) API DESIGN",
"",
"Base URL: /api/v1",
"",
"Standard success response:",
"```json",
"{",
"  \"success\": true,",
"  \"data\": {},",
"  \"meta\": { \"requestId\": \"req_123\" }",
"}",
"```",
"",
"Standard error response:",
"```json",
"{",
"  \"success\": false,",
"  \"error\": {",
"    \"code\": \"VALIDATION_ERROR\",",
"    \"message\": \"Invalid request payload\",",
"    \"details\": [{ \"field\": \"email\", \"message\": \"Invalid email\" }],",
"    \"requestId\": \"req_123\",",
"    \"timestamp\": \"2026-03-21T12:00:00.000Z\"",
"  }",
"}",
"```",
"",
"Authentication flow:",
"1. POST /auth/login with email/password.",
"2. Server validates credentials, returns short-lived access token and refresh token cookie.",
"3. Frontend sends Bearer access token for protected APIs.",
"4. On expiry, client calls /auth/refresh using secure cookie.",
"5. Logout revokes refresh token and clears session.",
"",
"Endpoint catalog:",
"- POST /auth/register",
"- POST /auth/login",
"- POST /auth/refresh",
"- POST /auth/logout",
"- GET  /auth/me",
"- POST /auth/forgot-password",
"- POST /auth/reset-password",
"- GET  /organizations/:orgId/projects",
"- POST /organizations/:orgId/projects",
"- GET  /projects/:projectId",
"- PUT  /projects/:projectId",
"- DELETE /projects/:projectId",
"- GET  /projects/:projectId/tasks",
"- POST /projects/:projectId/tasks",
"- GET  /tasks/:taskId",
"- PUT  /tasks/:taskId",
"- DELETE /tasks/:taskId",
"- POST /tasks/:taskId/assignees",
"- DELETE /tasks/:taskId/assignees/:userId",
"- GET  /tasks/:taskId/comments",
"- POST /tasks/:taskId/comments",
"",
"## 4) BACKEND IMPLEMENTATION",
"",
"Architecture:",
"- Controllers: request parsing + response mapping.",
"- Services: business policies and orchestration.",
"- Repositories: Prisma database operations only.",
"- Middleware: auth, RBAC, validation, rate limiting, error formatting.",
"",
"Example route and controller:",
"```ts",
"router.post(\"/projects/:projectId/tasks\", authMiddleware, validate(createTaskSchema), tasksController.create);",
"",
"export const tasksController = {",
"  create: async (req, res) => {",
"    const result = await tasksService.createTask({",
"      projectId: req.params.projectId,",
"      userId: req.user.id,",
"      payload: req.validatedBody",
"    });",
"    return res.status(201).json({ success: true, data: result });",
"  }",
"};",
"```",
"",
"Service example:",
"```ts",
"export const tasksService = {",
"  createTask: async ({ projectId, userId, payload }) => {",
"    const canAccess = await membershipRepository.canAccessProject(projectId, userId);",
"    if (!canAccess) throw new HttpError(403, \"FORBIDDEN\", \"Access denied\");",
"",
"    const taskNumber = await taskRepository.getNextTaskNumber(projectId);",
"    return taskRepository.create({ ...payload, projectId, taskNumber, reporterId: userId });",
"  }",
"};",
"```",
"",
"Repository example:",
"```ts",
"export const taskRepository = {",
"  getNextTaskNumber: async (projectId: string) => {",
"    const last = await prisma.task.findFirst({",
"      where: { projectId },",
"      orderBy: { taskNumber: \"desc\" },",
"      select: { taskNumber: true }",
"    });",
"    return (last?.taskNumber ?? 0) + 1;",
"  },",
"  create: (data) => prisma.task.create({ data })",
"};",
"```",
"",
"## 5) FRONTEND IMPLEMENTATION",
"",
"Pages:",
"- Home (marketing + CTA)",
"- Login/Register/Forgot Password",
"- Dashboard",
"- Projects list/details",
"- Task details with comments/assignments",
"",
"Reusable components:",
"- AppShell, Sidebar, Topbar",
"- Card, DataTable, Modal, FormField, Button, Toast",
"- Skeleton loaders and ErrorBoundary",
"",
"State management (Zustand):",
"- auth.store.ts for user/session state.",
"- project.store.ts for project listing/filter/pagination.",
"- task.store.ts for task board and optimistic updates.",
"",
"Example auth store:",
"```ts",
"type AuthState = {",
"  user: UserDto | null;",
"  accessToken: string | null;",
"  login: (email: string, password: string) => Promise<void>;",
"  logout: () => Promise<void>;",
"};",
"```",
"",
"Loading and error patterns:",
"- page-level skeleton while fetching.",
"- inline form validation errors.",
"- toast for async action results.",
"- retry CTA for recoverable request failures.",
"",
"## 6) DATA FLOW (VERY IMPORTANT)",
"",
"Step-by-step:",
"1. User submits action in UI (e.g., create task).",
"2. Frontend validates inputs and dispatches API call.",
"3. API route receives request and runs auth middleware.",
"4. Validation middleware checks schema and sanitizes payload.",
"5. Controller passes trusted data to service layer.",
"6. Service enforces business rules and permissions.",
"7. Repository executes Prisma queries against PostgreSQL.",
"8. DB returns transaction result.",
"9. Service maps domain result DTO.",
"10. Controller returns structured JSON response.",
"11. Frontend updates Zustand state and re-renders UI.",
"",
"## 7) SECURITY",
"",
"Security controls:",
"- JWT access token with short TTL (15m).",
"- Refresh token rotation and revocation list in DB.",
"- Password hashing with bcrypt (12 rounds minimum).",
"- Input validation with Zod at all boundaries.",
"- Rate limiting on auth and sensitive endpoints.",
"- Helmet security headers and CORS allowlist.",
"- Strict RBAC at middleware and service layers.",
"- Audit logs for privileged operations.",
"- Secure httpOnly cookies for refresh token.",
"- SQL injection prevention through Prisma parameterization.",
"",
"## 8) PERFORMANCE",
"",
"Performance plan:",
"- Next.js route-level code splitting and dynamic imports.",
"- Lazy loading non-critical widgets.",
"- SWR/React Query caching for GET resources.",
"- API pagination with cursor strategy.",
"- DB indexes for projectId/status/dueDate and join keys.",
"- CDN + immutable cache headers for static assets.",
"- Optimize LCP by SSR critical shell and reducing JS payload.",
"- Use image optimization and preconnect for critical origins.",
"",
"## 9) TESTING",
"",
"Testing strategy:",
"- Unit tests: services, utils, validators.",
"- API tests: supertest for routes, auth, RBAC, error contracts.",
"- E2E: Playwright for login -> dashboard -> create project -> create task -> comment -> logout.",
"",
"Example API test:",
"```ts",
"it(\"creates task when authorized\", async () => {",
"  const res = await request(app)",
"    .post(\"/api/v1/projects/p1/tasks\")",
"    .set(\"Authorization\", `Bearer ${token}`)",
"    .send({ title: \"Setup API\", priority: \"HIGH\" });",
"",
"  expect(res.status).toBe(201);",
"  expect(res.body.success).toBe(true);",
"});",
"```",
"",
"## 10) DEPLOYMENT",
"",
"Frontend deployment (Vercel):",
"- Deploy apps/web.",
"- Set NEXT_PUBLIC_API_URL and runtime env vars.",
"- Enable preview deployments per PR.",
"",
"Backend deployment (Node server):",
"- Deploy apps/api on Render/Fly/AWS ECS.",
"- Use Docker image with health endpoint /api/v1/health.",
"- Apply rolling deployments with zero downtime.",
"",
"Database deployment (Postgres cloud):",
"- Neon/Supabase/RDS managed PostgreSQL.",
"- Run prisma migrate deploy during release pipeline.",
"- Backup policy + PITR enabled.",
"",
"Production DevOps checklist:",
"- CI: lint + typecheck + unit + API tests + build.",
"- CD: migration -> deploy -> smoke test -> monitor.",
"- Observability: logs, metrics, tracing, alerting.",
"",
"## FINAL NOTES",
"- This architecture is scalable, maintainable, and follows strict separation of concerns.",
"- It supports multi-tenant growth, secure auth, and enterprise-grade operational practices.",
"- The same structure is ready for extension (notifications, billing, analytics, audit, webhooks)."
].join("\n");

const doc = new jsPDF({ unit: "pt", format: "a4" });
const pageWidth = doc.internal.pageSize.getWidth();
const pageHeight = doc.internal.pageSize.getHeight();
const margin = 46;
const usableWidth = pageWidth - margin * 2;
let y = margin;
let codeMode = false;

const addPageIfNeeded = (needed = 14) => {
  if (y + needed > pageHeight - margin) {
    doc.addPage();
    y = margin;
  }
};

const drawLine = (line) => {
  let font = "helvetica";
  let style = "normal";
  let size = 11;
  let extraSpace = 0;

  if (line.startsWith("# ")) {
    font = "helvetica"; style = "bold"; size = 18;
    line = line.replace(/^#\s+/, "");
    extraSpace = 8;
  } else if (line.startsWith("## ")) {
    font = "helvetica"; style = "bold"; size = 14;
    line = line.replace(/^##\s+/, "");
    extraSpace = 6;
  } else if (line.startsWith("- ")) {
    line = "  - " + line.slice(2);
  }

  if (codeMode) {
    font = "courier";
    style = "normal";
    size = 9;
  }

  doc.setFont(font, style);
  doc.setFontSize(size);

  const wrapped = doc.splitTextToSize(line || " ", usableWidth);
  for (const w of wrapped) {
    addPageIfNeeded(size + 5);
    doc.text(w, margin, y);
    y += size + 4;
  }

  if (!line.trim()) y += 3;
  if (extraSpace) y += extraSpace;
};

for (const rawLine of content.split("\n")) {
  if (rawLine.trim().startsWith("```")) {
    codeMode = !codeMode;
    drawLine(rawLine.trim());
    continue;
  }
  drawLine(rawLine);
}

const outPath = "E:/Master V/Complete_FullStack_Architecture_Documentation.pdf";
const bytes = doc.output("arraybuffer");
fs.writeFileSync(outPath, Buffer.from(bytes));
console.log(outPath);
